sudo: true
language: scala
scala: 2.6.12
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
script:
- scripts/build.sh
env:
  global:
  - secure: MTwmzpS9B8+oGHutRbNIDIFG8DpaJ3w8U/acHGKoOh6Q6UvNEPJMD5d6u96VNJsnidnFt/ppvnPE6FuHHqGf/T9mQYnxTCUgxQqacXIGsWche25vGSZohjdw0Qszs540smnT2bawXXhIDX4AZjy9Vx7Kgm1La+7H2nh8WRsQqglcZV9DMH3z7/4QBOPPMziFvufVVj/D02Wa5fWRWnWv09ipGfzmPrLZC0Mn4j7QgfVPX0x923myqcHS1toO8u3bjuiaQ2V3H8w6UsjUWs30lsMLpxaWva3F4Qv3AXizzWZYXjy4M91ExoqeM6u6jBlojtlYAAbP06xz1i6gXNavoLL6Hrhv3MeGI4wrcRsmJ9mjALcuGlKz54N43JlxGX2rgRsmRG7s9O5uugUFkxTFpJd8S7hJu7itVj5zUOUdJFzDmPvePC+tlCrouTfjALeJfvAxVU9WxZJPZjyYhcAFuOYfPJMQu+Q+QDe9SK3BJFPoEfpf3zosghq+NRYhN5AtYODy4hLZoHQajwXNh6rSdQ23iV1ati01C+itMz/4Q+WjKQCsVf0dMHf1T6RSQ3UiYBWPPGDdGWLEq58ugOgpVSP3+KEbtBDoahF67t8sdyJzfSNyIbi1vY7AOUN1oQHAeK70DjsNbdybhYh3OTWY/+54EwZiDq9qXjNU6hN4Eu8=
  - secure: VFWL3Mc+83dF9lCJxWcF5+uLn16PuxMOiUj1Ep+a+aMPJuYKldYrlgME73RTWZekE20J6O8QhFUv0DElc9W8aC49onUXO83xUMzv5uWgFLc0AUx/XJTQIvSIT/IbY5RkW7Ir8uJSTRcQroAphxqpJkxnTlawRg26/tY595/oN9YLnz9kmjWnyJ87L5PFwCJ9wzgxN5xw+lZAFgqJbfwC+/vF8GzrFfkVnJc2G8fNAjx5QexF0JVEwKjP50fv4o8o9OV8AHeTDDF4gMngH9CIggEwJDEDOEvcoXRz0Rl7IecQUt9LCf1oKmRPx+Ar9mfE0AFSv39IXnpjJvZJc+fn7idkHqNKzIewZ4ctk4dA3/bk+CDK+J+dsn7eP+RBWPjxSOazFlpXFjC09e+1L7Iv0qGd1Jz8Mg3ytRlOGxtjYEzSnjoXqBq968o17jUhUXDTBsan1c9s1JE9Oet0LMf14W+0yc/G9jqqeY/EF1dV40V3WcGAfrEn4sD3NaO9W4Au051Tkg7+qTkNlGXzOM9OuHah/D3vGJfQtLyEQB/eVd/A/sXEEj8u5Ob4mOllBCqZbbsEd0Wo9pi0CP0bhwq0+ZmD0yr5Xj/4ettqwprwapFgkDwvDirLwS1bmOe3t7WkYI8oveDvpmGK8AwJk9+YVNJ/lMWqyuOWrY0q6l9FwWQ=
